#!/usr/bin/env python
import json
import os
import pytest
import sys
import shutil


if 'PYTEST_WRAPPER_ARGS' not in os.environ:
    os.environ['PYTEST_WRAPPER_ARGS'] = json.dumps(sys.argv[1:])
    os.environ['PYTHONPATH'] = os.path.abspath('.venv3/lib/python3.5/site-packages')
    blender = shutil.which('blender')
    if not blender:
        sys.stderr.write('blender not found; make sure the `blender` command is on your path and try again\n')
        sys.exit(1)
    os.execl(blender, 'blender', '--python', __file__, '--background')
else:
    args = json.loads(os.environ['PYTEST_WRAPPER_ARGS'])
    pytest.main(args)
